/******************************* Problem 2: Even Fibonacci numbers ***************************************/

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include<iostream>
using namespace std;

int fab(int n){
    if(n==1 || n==0)
        return n;
    return (fab(n-1)+fab(n-2));
    
}

int main(){
  int sum=0;
  for(int i=0;fab(i)<4000000;i++){
    if(fab(i)%2==0)
        sum=sum+fab(i);
  }
    cout<<sum;
    return 0;
}
//Ans 4613732

